services:
  simulator:
    container_name: go-simulator
    build:
      context: ../simulator
      dockerfile: Dockerfile
      target: runtime
    environment:
      - PATIENTS=3
      - BROKERS=kafka:9092
      - NO_KAFKA=true
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:8.2.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 2-pVRRCrSWqlNUBBlKPRIQ  # hardcoded for local dev only
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 10
  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:8.2.0
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/subjects" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:2.26.3-pg16
    environment:
      POSTGRES_USER: icu
      POSTGRES_PASSWORD: icu
      POSTGRES_DB: icu
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U icu" ]
      interval: 5s
      timeout: 3s
      retries: 10
  pgweb:
    image: sosedoff/pgweb
    container_name: timescaledb-pgweb
    depends_on:
      - timescaledb
    ports:
      - "8082:8081"
    environment:
      PGWEB_DATABASE_URL: "postgresql://icu:icu@timescaledb:5432/icu?sslmode=disable"
    restart: always
  schema-registry-init:
    image: alpine:3.21
    depends_on:
      schema-registry:
        condition: service_healthy
    volumes:
      - ./schemas:/schemas
      - ./scripts:/scripts
    entrypoint: [ "/bin/sh", "/scripts/register_schemas.sh" ]
    restart: "no"
volumes:
  kafka-data:
  timescaledb-data:
