apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    user: icu
    secureJsonData:
      password: icu
    jsonData:
      database: icu
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    isDefault: true
    editable: false

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity
    editable: false
    jsonData:
      allowed_hosts:
        - http://delta-reader:5000